package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacActor;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_actor", primaryKey = "actor_id")
public class MacActor extends BaseMacActor<MacActor> {
	
}
