package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacAdmin;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_admin", primaryKey = "admin_id")
public class MacAdmin extends BaseMacAdmin<MacAdmin> {
	
}
