package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacArt;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_art", primaryKey = "art_id")
public class MacArt extends BaseMacArt<MacArt> {
	
}
