package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacCjHistory;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_cj_history", primaryKey = "md5")
public class MacCjHistory extends BaseMacCjHistory<MacCjHistory> {
	
}
