package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacCollect;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_collect", primaryKey = "collect_id")
public class MacCollect extends BaseMacCollect<MacCollect> {
	
}
