package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacCjNode;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_cj_node", primaryKey = "nodeid")
public class MacCjNode extends BaseMacCjNode<MacCjNode> {
	
}
