package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacCard;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_card", primaryKey = "card_id")
public class MacCard extends BaseMacCard<MacCard> {
	
}
