package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacComment;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_comment", primaryKey = "comment_id")
public class MacComment extends BaseMacComment<MacComment> {
	
}
