package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacCjContent;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_cj_content", primaryKey = "id")
public class MacCjContent extends BaseMacCjContent<MacCjContent> {
	
}
