package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacGbook;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_gbook", primaryKey = "gbook_id")
public class MacGbook extends BaseMacGbook<MacGbook> {
	
}
