package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacGroup;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_group", primaryKey = "group_id")
public class MacGroup extends BaseMacGroup<MacGroup> {
	
}
