package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacLink;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_link", primaryKey = "link_id")
public class MacLink extends BaseMacLink<MacLink> {
	
}
