package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacMsg;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_msg", primaryKey = "msg_id")
public class MacMsg extends BaseMacMsg<MacMsg> {
	
}
