package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacOrder;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_order", primaryKey = "order_id")
public class MacOrder extends BaseMacOrder<MacOrder> {
	
}
