package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_role", primaryKey = "role_id")
public class MacRole extends BaseMacRole<MacRole> {
	
}
