package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacType;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_type", primaryKey = "type_id")
public class MacType extends BaseMacType<MacType> {
	
}
