package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacTopic;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_topic", primaryKey = "topic_id")
public class MacTopic extends BaseMacTopic<MacTopic> {
	
}
