package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacUlog;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_ulog", primaryKey = "ulog_id")
public class MacUlog extends BaseMacUlog<MacUlog> {
	
}
