package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_user", primaryKey = "user_id")
public class MacUser extends BaseMacUser<MacUser> {
	
}
