package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacVodDown;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_vod_down", primaryKey = "id")
public class MacVodDown extends BaseMacVodDown<MacVodDown> {
	
}
