package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacVodRes;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_vod_res", primaryKey = "id")
public class MacVodRes extends BaseMacVodRes<MacVodRes> {
	
}
