package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacVodPlayer;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_vod_player", primaryKey = "id")
public class MacVodPlayer extends BaseMacVodPlayer<MacVodPlayer> {
	
}
