package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;

import java.util.List;

import com.lzx.movie.service.entity.model.base.BaseMacVod;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_vod", primaryKey = "vod_id")
public class MacVod extends BaseMacVod<MacVod> {
	
	
	private List<MacVodRes> macVodResList;

	public List<MacVodRes> getMacVodResList() {
		return macVodResList;
	}

	public void setMacVodResList(List<MacVodRes> macVodResList) {
		this.macVodResList = macVodResList;
	}

	
	
}
