package com.lzx.movie.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.movie.service.entity.model.base.BaseMacVisit;

/**
 * Generated by Jboot.
 */
@Table(tableName = "mac_visit", primaryKey = "visit_id")
public class MacVisit extends BaseMacVisit<MacVisit> {
	
}
