package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacArt<M extends BaseMacArt<M>> extends JbootModel<M> implements IBean {

	public void setArtId(java.lang.Long artId) {
		set("art_id", artId);
	}
	
	public java.lang.Long getArtId() {
		return getLong("art_id");
	}

	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	public void setTypeId1(java.lang.Integer typeId1) {
		set("type_id_1", typeId1);
	}
	
	public java.lang.Integer getTypeId1() {
		return getInt("type_id_1");
	}

	public void setGroupId(java.lang.Integer groupId) {
		set("group_id", groupId);
	}
	
	public java.lang.Integer getGroupId() {
		return getInt("group_id");
	}

	public void setArtName(java.lang.String artName) {
		set("art_name", artName);
	}
	
	public java.lang.String getArtName() {
		return getStr("art_name");
	}

	public void setArtSub(java.lang.String artSub) {
		set("art_sub", artSub);
	}
	
	public java.lang.String getArtSub() {
		return getStr("art_sub");
	}

	public void setArtEn(java.lang.String artEn) {
		set("art_en", artEn);
	}
	
	public java.lang.String getArtEn() {
		return getStr("art_en");
	}

	public void setArtStatus(java.lang.Boolean artStatus) {
		set("art_status", artStatus);
	}
	
	public java.lang.Boolean getArtStatus() {
		return get("art_status");
	}

	public void setArtLetter(java.lang.String artLetter) {
		set("art_letter", artLetter);
	}
	
	public java.lang.String getArtLetter() {
		return getStr("art_letter");
	}

	public void setArtColor(java.lang.String artColor) {
		set("art_color", artColor);
	}
	
	public java.lang.String getArtColor() {
		return getStr("art_color");
	}

	public void setArtFrom(java.lang.String artFrom) {
		set("art_from", artFrom);
	}
	
	public java.lang.String getArtFrom() {
		return getStr("art_from");
	}

	public void setArtAuthor(java.lang.String artAuthor) {
		set("art_author", artAuthor);
	}
	
	public java.lang.String getArtAuthor() {
		return getStr("art_author");
	}

	public void setArtTag(java.lang.String artTag) {
		set("art_tag", artTag);
	}
	
	public java.lang.String getArtTag() {
		return getStr("art_tag");
	}

	public void setArtClass(java.lang.String artClass) {
		set("art_class", artClass);
	}
	
	public java.lang.String getArtClass() {
		return getStr("art_class");
	}

	public void setArtPic(java.lang.String artPic) {
		set("art_pic", artPic);
	}
	
	public java.lang.String getArtPic() {
		return getStr("art_pic");
	}

	public void setArtPicThumb(java.lang.String artPicThumb) {
		set("art_pic_thumb", artPicThumb);
	}
	
	public java.lang.String getArtPicThumb() {
		return getStr("art_pic_thumb");
	}

	public void setArtPicSlide(java.lang.String artPicSlide) {
		set("art_pic_slide", artPicSlide);
	}
	
	public java.lang.String getArtPicSlide() {
		return getStr("art_pic_slide");
	}

	public void setArtBlurb(java.lang.String artBlurb) {
		set("art_blurb", artBlurb);
	}
	
	public java.lang.String getArtBlurb() {
		return getStr("art_blurb");
	}

	public void setArtRemarks(java.lang.String artRemarks) {
		set("art_remarks", artRemarks);
	}
	
	public java.lang.String getArtRemarks() {
		return getStr("art_remarks");
	}

	public void setArtJumpurl(java.lang.String artJumpurl) {
		set("art_jumpurl", artJumpurl);
	}
	
	public java.lang.String getArtJumpurl() {
		return getStr("art_jumpurl");
	}

	public void setArtTpl(java.lang.String artTpl) {
		set("art_tpl", artTpl);
	}
	
	public java.lang.String getArtTpl() {
		return getStr("art_tpl");
	}

	public void setArtLevel(java.lang.Boolean artLevel) {
		set("art_level", artLevel);
	}
	
	public java.lang.Boolean getArtLevel() {
		return get("art_level");
	}

	public void setArtLock(java.lang.Boolean artLock) {
		set("art_lock", artLock);
	}
	
	public java.lang.Boolean getArtLock() {
		return get("art_lock");
	}

	public void setArtUp(java.lang.Integer artUp) {
		set("art_up", artUp);
	}
	
	public java.lang.Integer getArtUp() {
		return getInt("art_up");
	}

	public void setArtDown(java.lang.Integer artDown) {
		set("art_down", artDown);
	}
	
	public java.lang.Integer getArtDown() {
		return getInt("art_down");
	}

	public void setArtHits(java.lang.Integer artHits) {
		set("art_hits", artHits);
	}
	
	public java.lang.Integer getArtHits() {
		return getInt("art_hits");
	}

	public void setArtHitsDay(java.lang.Integer artHitsDay) {
		set("art_hits_day", artHitsDay);
	}
	
	public java.lang.Integer getArtHitsDay() {
		return getInt("art_hits_day");
	}

	public void setArtHitsWeek(java.lang.Integer artHitsWeek) {
		set("art_hits_week", artHitsWeek);
	}
	
	public java.lang.Integer getArtHitsWeek() {
		return getInt("art_hits_week");
	}

	public void setArtHitsMonth(java.lang.Integer artHitsMonth) {
		set("art_hits_month", artHitsMonth);
	}
	
	public java.lang.Integer getArtHitsMonth() {
		return getInt("art_hits_month");
	}

	public void setArtTime(java.lang.Long artTime) {
		set("art_time", artTime);
	}
	
	public java.lang.Long getArtTime() {
		return getLong("art_time");
	}

	public void setArtTimeAdd(java.lang.Long artTimeAdd) {
		set("art_time_add", artTimeAdd);
	}
	
	public java.lang.Long getArtTimeAdd() {
		return getLong("art_time_add");
	}

	public void setArtTimeHits(java.lang.Long artTimeHits) {
		set("art_time_hits", artTimeHits);
	}
	
	public java.lang.Long getArtTimeHits() {
		return getLong("art_time_hits");
	}

	public void setArtTimeMake(java.lang.Long artTimeMake) {
		set("art_time_make", artTimeMake);
	}
	
	public java.lang.Long getArtTimeMake() {
		return getLong("art_time_make");
	}

	public void setArtScore(java.math.BigDecimal artScore) {
		set("art_score", artScore);
	}
	
	public java.math.BigDecimal getArtScore() {
		return get("art_score");
	}

	public void setArtScoreAll(java.lang.Integer artScoreAll) {
		set("art_score_all", artScoreAll);
	}
	
	public java.lang.Integer getArtScoreAll() {
		return getInt("art_score_all");
	}

	public void setArtScoreNum(java.lang.Integer artScoreNum) {
		set("art_score_num", artScoreNum);
	}
	
	public java.lang.Integer getArtScoreNum() {
		return getInt("art_score_num");
	}

	public void setArtRelArt(java.lang.String artRelArt) {
		set("art_rel_art", artRelArt);
	}
	
	public java.lang.String getArtRelArt() {
		return getStr("art_rel_art");
	}

	public void setArtRelVod(java.lang.String artRelVod) {
		set("art_rel_vod", artRelVod);
	}
	
	public java.lang.String getArtRelVod() {
		return getStr("art_rel_vod");
	}

	public void setArtTitle(java.lang.String artTitle) {
		set("art_title", artTitle);
	}
	
	public java.lang.String getArtTitle() {
		return getStr("art_title");
	}

	public void setArtNote(java.lang.String artNote) {
		set("art_note", artNote);
	}
	
	public java.lang.String getArtNote() {
		return getStr("art_note");
	}

	public void setArtContent(java.lang.String artContent) {
		set("art_content", artContent);
	}
	
	public java.lang.String getArtContent() {
		return getStr("art_content");
	}

}
