package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacOrder<M extends BaseMacOrder<M>> extends JbootModel<M> implements IBean {

	public void setOrderId(java.lang.Long orderId) {
		set("order_id", orderId);
	}
	
	public java.lang.Long getOrderId() {
		return getLong("order_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setOrderStatus(java.lang.Boolean orderStatus) {
		set("order_status", orderStatus);
	}
	
	public java.lang.Boolean getOrderStatus() {
		return get("order_status");
	}

	public void setOrderCode(java.lang.String orderCode) {
		set("order_code", orderCode);
	}
	
	public java.lang.String getOrderCode() {
		return getStr("order_code");
	}

	public void setOrderPrice(java.math.BigDecimal orderPrice) {
		set("order_price", orderPrice);
	}
	
	public java.math.BigDecimal getOrderPrice() {
		return get("order_price");
	}

	public void setOrderTime(java.lang.Long orderTime) {
		set("order_time", orderTime);
	}
	
	public java.lang.Long getOrderTime() {
		return getLong("order_time");
	}

	public void setOrderPoints(java.lang.Integer orderPoints) {
		set("order_points", orderPoints);
	}
	
	public java.lang.Integer getOrderPoints() {
		return getInt("order_points");
	}

	public void setOrderPayType(java.lang.String orderPayType) {
		set("order_pay_type", orderPayType);
	}
	
	public java.lang.String getOrderPayType() {
		return getStr("order_pay_type");
	}

	public void setOrderPayTime(java.lang.Long orderPayTime) {
		set("order_pay_time", orderPayTime);
	}
	
	public java.lang.Long getOrderPayTime() {
		return getLong("order_pay_time");
	}

	public void setOrderRemarks(java.lang.String orderRemarks) {
		set("order_remarks", orderRemarks);
	}
	
	public java.lang.String getOrderRemarks() {
		return getStr("order_remarks");
	}

}
