package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacMsg<M extends BaseMacMsg<M>> extends JbootModel<M> implements IBean {

	public void setMsgId(java.lang.Long msgId) {
		set("msg_id", msgId);
	}
	
	public java.lang.Long getMsgId() {
		return getLong("msg_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setMsgType(java.lang.Boolean msgType) {
		set("msg_type", msgType);
	}
	
	public java.lang.Boolean getMsgType() {
		return get("msg_type");
	}

	public void setMsgStatus(java.lang.Boolean msgStatus) {
		set("msg_status", msgStatus);
	}
	
	public java.lang.Boolean getMsgStatus() {
		return get("msg_status");
	}

	public void setMsgTo(java.lang.String msgTo) {
		set("msg_to", msgTo);
	}
	
	public java.lang.String getMsgTo() {
		return getStr("msg_to");
	}

	public void setMsgCode(java.lang.String msgCode) {
		set("msg_code", msgCode);
	}
	
	public java.lang.String getMsgCode() {
		return getStr("msg_code");
	}

	public void setMsgContent(java.lang.String msgContent) {
		set("msg_content", msgContent);
	}
	
	public java.lang.String getMsgContent() {
		return getStr("msg_content");
	}

	public void setMsgTime(java.lang.Long msgTime) {
		set("msg_time", msgTime);
	}
	
	public java.lang.Long getMsgTime() {
		return getLong("msg_time");
	}

}
