package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacType<M extends BaseMacType<M>> extends JbootModel<M> implements IBean {

	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	public void setTypeName(java.lang.String typeName) {
		set("type_name", typeName);
	}
	
	public java.lang.String getTypeName() {
		return getStr("type_name");
	}

	public void setTypeEn(java.lang.String typeEn) {
		set("type_en", typeEn);
	}
	
	public java.lang.String getTypeEn() {
		return getStr("type_en");
	}

	public void setTypeSort(java.lang.Integer typeSort) {
		set("type_sort", typeSort);
	}
	
	public java.lang.Integer getTypeSort() {
		return getInt("type_sort");
	}

	public void setTypeMid(java.lang.Integer typeMid) {
		set("type_mid", typeMid);
	}
	
	public java.lang.Integer getTypeMid() {
		return getInt("type_mid");
	}

	public void setTypePid(java.lang.Integer typePid) {
		set("type_pid", typePid);
	}
	
	public java.lang.Integer getTypePid() {
		return getInt("type_pid");
	}

	public void setTypeStatus(java.lang.Boolean typeStatus) {
		set("type_status", typeStatus);
	}
	
	public java.lang.Boolean getTypeStatus() {
		return get("type_status");
	}

	public void setTypeTpl(java.lang.String typeTpl) {
		set("type_tpl", typeTpl);
	}
	
	public java.lang.String getTypeTpl() {
		return getStr("type_tpl");
	}

	public void setTypeTplList(java.lang.String typeTplList) {
		set("type_tpl_list", typeTplList);
	}
	
	public java.lang.String getTypeTplList() {
		return getStr("type_tpl_list");
	}

	public void setTypeTplDetail(java.lang.String typeTplDetail) {
		set("type_tpl_detail", typeTplDetail);
	}
	
	public java.lang.String getTypeTplDetail() {
		return getStr("type_tpl_detail");
	}

	public void setTypeTplPlay(java.lang.String typeTplPlay) {
		set("type_tpl_play", typeTplPlay);
	}
	
	public java.lang.String getTypeTplPlay() {
		return getStr("type_tpl_play");
	}

	public void setTypeTplDown(java.lang.String typeTplDown) {
		set("type_tpl_down", typeTplDown);
	}
	
	public java.lang.String getTypeTplDown() {
		return getStr("type_tpl_down");
	}

	public void setTypeKey(java.lang.String typeKey) {
		set("type_key", typeKey);
	}
	
	public java.lang.String getTypeKey() {
		return getStr("type_key");
	}

	public void setTypeDes(java.lang.String typeDes) {
		set("type_des", typeDes);
	}
	
	public java.lang.String getTypeDes() {
		return getStr("type_des");
	}

	public void setTypeTitle(java.lang.String typeTitle) {
		set("type_title", typeTitle);
	}
	
	public java.lang.String getTypeTitle() {
		return getStr("type_title");
	}

	public void setTypeUnion(java.lang.String typeUnion) {
		set("type_union", typeUnion);
	}
	
	public java.lang.String getTypeUnion() {
		return getStr("type_union");
	}

	public void setTypeExtend(java.lang.String typeExtend) {
		set("type_extend", typeExtend);
	}
	
	public java.lang.String getTypeExtend() {
		return getStr("type_extend");
	}

}
