package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacCjHistory<M extends BaseMacCjHistory<M>> extends JbootModel<M> implements IBean {

	public void setMd5(java.lang.String md5) {
		set("md5", md5);
	}
	
	public java.lang.String getMd5() {
		return getStr("md5");
	}

}
