package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacCard<M extends BaseMacCard<M>> extends JbootModel<M> implements IBean {

	public void setCardId(java.lang.Long cardId) {
		set("card_id", cardId);
	}
	
	public java.lang.Long getCardId() {
		return getLong("card_id");
	}

	public void setCardNo(java.lang.String cardNo) {
		set("card_no", cardNo);
	}
	
	public java.lang.String getCardNo() {
		return getStr("card_no");
	}

	public void setCardPwd(java.lang.String cardPwd) {
		set("card_pwd", cardPwd);
	}
	
	public java.lang.String getCardPwd() {
		return getStr("card_pwd");
	}

	public void setCardMoney(java.lang.Integer cardMoney) {
		set("card_money", cardMoney);
	}
	
	public java.lang.Integer getCardMoney() {
		return getInt("card_money");
	}

	public void setCardPoints(java.lang.Integer cardPoints) {
		set("card_points", cardPoints);
	}
	
	public java.lang.Integer getCardPoints() {
		return getInt("card_points");
	}

	public void setCardUseStatus(java.lang.Boolean cardUseStatus) {
		set("card_use_status", cardUseStatus);
	}
	
	public java.lang.Boolean getCardUseStatus() {
		return get("card_use_status");
	}

	public void setCardSaleStatus(java.lang.Boolean cardSaleStatus) {
		set("card_sale_status", cardSaleStatus);
	}
	
	public java.lang.Boolean getCardSaleStatus() {
		return get("card_sale_status");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setCardAddTime(java.lang.Long cardAddTime) {
		set("card_add_time", cardAddTime);
	}
	
	public java.lang.Long getCardAddTime() {
		return getLong("card_add_time");
	}

	public void setCardUseTime(java.lang.Long cardUseTime) {
		set("card_use_time", cardUseTime);
	}
	
	public java.lang.Long getCardUseTime() {
		return getLong("card_use_time");
	}

}
