package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacActor<M extends BaseMacActor<M>> extends JbootModel<M> implements IBean {

	public void setActorId(java.lang.Long actorId) {
		set("actor_id", actorId);
	}
	
	public java.lang.Long getActorId() {
		return getLong("actor_id");
	}
	public void setActorName(java.lang.String actorName) {

		set("actor_name", actorName);
	}
	
	public java.lang.String getActorName() {
		return getStr("actor_name");
	}

	public void setActorEn(java.lang.String actorEn) {
		set("actor_en", actorEn);
	}
	
	public java.lang.String getActorEn() {
		return getStr("actor_en");
	}

	public void setActorAlias(java.lang.String actorAlias) {
		set("actor_alias", actorAlias);
	}
	
	public java.lang.String getActorAlias() {
		return getStr("actor_alias");
	}

	public void setActorStatus(java.lang.Boolean actorStatus) {
		set("actor_status", actorStatus);
	}
	
	public java.lang.Boolean getActorStatus() {
		return get("actor_status");
	}

	public void setActorLock(java.lang.Boolean actorLock) {
		set("actor_lock", actorLock);
	}
	
	public java.lang.Boolean getActorLock() {
		return get("actor_lock");
	}

	public void setActorLetter(java.lang.String actorLetter) {
		set("actor_letter", actorLetter);
	}
	
	public java.lang.String getActorLetter() {
		return getStr("actor_letter");
	}

	public void setActorSex(java.lang.String actorSex) {
		set("actor_sex", actorSex);
	}
	
	public java.lang.String getActorSex() {
		return getStr("actor_sex");
	}

	public void setActorColor(java.lang.String actorColor) {
		set("actor_color", actorColor);
	}
	
	public java.lang.String getActorColor() {
		return getStr("actor_color");
	}

	public void setActorPic(java.lang.String actorPic) {
		set("actor_pic", actorPic);
	}
	
	public java.lang.String getActorPic() {
		return getStr("actor_pic");
	}

	public void setActorBlurb(java.lang.String actorBlurb) {
		set("actor_blurb", actorBlurb);
	}
	
	public java.lang.String getActorBlurb() {
		return getStr("actor_blurb");
	}

	public void setActorRemarks(java.lang.String actorRemarks) {
		set("actor_remarks", actorRemarks);
	}
	
	public java.lang.String getActorRemarks() {
		return getStr("actor_remarks");
	}

	public void setActorArea(java.lang.String actorArea) {
		set("actor_area", actorArea);
	}
	
	public java.lang.String getActorArea() {
		return getStr("actor_area");
	}

	public void setActorHeight(java.lang.String actorHeight) {
		set("actor_height", actorHeight);
	}
	
	public java.lang.String getActorHeight() {
		return getStr("actor_height");
	}

	public void setActorWeight(java.lang.String actorWeight) {
		set("actor_weight", actorWeight);
	}
	
	public java.lang.String getActorWeight() {
		return getStr("actor_weight");
	}

	public void setActorBirthday(java.lang.String actorBirthday) {
		set("actor_birthday", actorBirthday);
	}
	
	public java.lang.String getActorBirthday() {
		return getStr("actor_birthday");
	}

	public void setActorBirtharea(java.lang.String actorBirtharea) {
		set("actor_birtharea", actorBirtharea);
	}
	
	public java.lang.String getActorBirtharea() {
		return getStr("actor_birtharea");
	}

	public void setActorBlood(java.lang.String actorBlood) {
		set("actor_blood", actorBlood);
	}
	
	public java.lang.String getActorBlood() {
		return getStr("actor_blood");
	}

	public void setActorStarsign(java.lang.String actorStarsign) {
		set("actor_starsign", actorStarsign);
	}
	
	public java.lang.String getActorStarsign() {
		return getStr("actor_starsign");
	}

	public void setActorSchool(java.lang.String actorSchool) {
		set("actor_school", actorSchool);
	}
	
	public java.lang.String getActorSchool() {
		return getStr("actor_school");
	}

	public void setActorWorks(java.lang.String actorWorks) {
		set("actor_works", actorWorks);
	}
	
	public java.lang.String getActorWorks() {
		return getStr("actor_works");
	}

	public void setActorLevel(java.lang.Boolean actorLevel) {
		set("actor_level", actorLevel);
	}
	
	public java.lang.Boolean getActorLevel() {
		return get("actor_level");
	}

	public void setActorTime(java.lang.Long actorTime) {
		set("actor_time", actorTime);
	}
	
	public java.lang.Long getActorTime() {
		return getLong("actor_time");
	}

	public void setActorTimeAdd(java.lang.Long actorTimeAdd) {
		set("actor_time_add", actorTimeAdd);
	}
	
	public java.lang.Long getActorTimeAdd() {
		return getLong("actor_time_add");
	}

	public void setActorTimeHits(java.lang.Long actorTimeHits) {
		set("actor_time_hits", actorTimeHits);
	}
	
	public java.lang.Long getActorTimeHits() {
		return getLong("actor_time_hits");
	}

	public void setActorTimeMake(java.lang.Long actorTimeMake) {
		set("actor_time_make", actorTimeMake);
	}
	
	public java.lang.Long getActorTimeMake() {
		return getLong("actor_time_make");
	}

	public void setActorHits(java.lang.Integer actorHits) {
		set("actor_hits", actorHits);
	}
	
	public java.lang.Integer getActorHits() {
		return getInt("actor_hits");
	}

	public void setActorHitsDay(java.lang.Integer actorHitsDay) {
		set("actor_hits_day", actorHitsDay);
	}
	
	public java.lang.Integer getActorHitsDay() {
		return getInt("actor_hits_day");
	}

	public void setActorHitsWeek(java.lang.Integer actorHitsWeek) {
		set("actor_hits_week", actorHitsWeek);
	}
	
	public java.lang.Integer getActorHitsWeek() {
		return getInt("actor_hits_week");
	}

	public void setActorHitsMonth(java.lang.Integer actorHitsMonth) {
		set("actor_hits_month", actorHitsMonth);
	}
	
	public java.lang.Integer getActorHitsMonth() {
		return getInt("actor_hits_month");
	}

	public void setActorScore(java.math.BigDecimal actorScore) {
		set("actor_score", actorScore);
	}
	
	public java.math.BigDecimal getActorScore() {
		return get("actor_score");
	}

	public void setActorScoreAll(java.lang.Integer actorScoreAll) {
		set("actor_score_all", actorScoreAll);
	}
	
	public java.lang.Integer getActorScoreAll() {
		return getInt("actor_score_all");
	}

	public void setActorScoreNum(java.lang.Integer actorScoreNum) {
		set("actor_score_num", actorScoreNum);
	}
	
	public java.lang.Integer getActorScoreNum() {
		return getInt("actor_score_num");
	}

	public void setActorUp(java.lang.Integer actorUp) {
		set("actor_up", actorUp);
	}
	
	public java.lang.Integer getActorUp() {
		return getInt("actor_up");
	}

	public void setActorDown(java.lang.Integer actorDown) {
		set("actor_down", actorDown);
	}
	
	public java.lang.Integer getActorDown() {
		return getInt("actor_down");
	}

	public void setActorTpl(java.lang.String actorTpl) {
		set("actor_tpl", actorTpl);
	}
	
	public java.lang.String getActorTpl() {
		return getStr("actor_tpl");
	}

	public void setActorJumpurl(java.lang.String actorJumpurl) {
		set("actor_jumpurl", actorJumpurl);
	}
	
	public java.lang.String getActorJumpurl() {
		return getStr("actor_jumpurl");
	}

	public void setActorContent(java.lang.String actorContent) {
		set("actor_content", actorContent);
	}
	
	public java.lang.String getActorContent() {
		return getStr("actor_content");
	}

}
