package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacGroup<M extends BaseMacGroup<M>> extends JbootModel<M> implements IBean {

	public void setGroupId(java.lang.Integer groupId) {
		set("group_id", groupId);
	}
	
	public java.lang.Integer getGroupId() {
		return getInt("group_id");
	}

	public void setGroupName(java.lang.String groupName) {
		set("group_name", groupName);
	}
	
	public java.lang.String getGroupName() {
		return getStr("group_name");
	}

	public void setGroupStatus(java.lang.Boolean groupStatus) {
		set("group_status", groupStatus);
	}
	
	public java.lang.Boolean getGroupStatus() {
		return get("group_status");
	}

	public void setGroupType(java.lang.String groupType) {
		set("group_type", groupType);
	}
	
	public java.lang.String getGroupType() {
		return getStr("group_type");
	}

	public void setGroupPopedom(java.lang.String groupPopedom) {
		set("group_popedom", groupPopedom);
	}
	
	public java.lang.String getGroupPopedom() {
		return getStr("group_popedom");
	}

	public void setGroupPointsDay(java.lang.Integer groupPointsDay) {
		set("group_points_day", groupPointsDay);
	}
	
	public java.lang.Integer getGroupPointsDay() {
		return getInt("group_points_day");
	}

	public void setGroupPointsWeek(java.lang.Integer groupPointsWeek) {
		set("group_points_week", groupPointsWeek);
	}
	
	public java.lang.Integer getGroupPointsWeek() {
		return getInt("group_points_week");
	}

	public void setGroupPointsMonth(java.lang.Integer groupPointsMonth) {
		set("group_points_month", groupPointsMonth);
	}
	
	public java.lang.Integer getGroupPointsMonth() {
		return getInt("group_points_month");
	}

	public void setGroupPointsYear(java.lang.Integer groupPointsYear) {
		set("group_points_year", groupPointsYear);
	}
	
	public java.lang.Integer getGroupPointsYear() {
		return getInt("group_points_year");
	}

	public void setGroupPointsFree(java.lang.Boolean groupPointsFree) {
		set("group_points_free", groupPointsFree);
	}
	
	public java.lang.Boolean getGroupPointsFree() {
		return get("group_points_free");
	}

}
