package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacLink<M extends BaseMacLink<M>> extends JbootModel<M> implements IBean {

	public void setLinkId(java.lang.Integer linkId) {
		set("link_id", linkId);
	}
	
	public java.lang.Integer getLinkId() {
		return getInt("link_id");
	}

	public void setLinkType(java.lang.Boolean linkType) {
		set("link_type", linkType);
	}
	
	public java.lang.Boolean getLinkType() {
		return get("link_type");
	}

	public void setLinkName(java.lang.String linkName) {
		set("link_name", linkName);
	}
	
	public java.lang.String getLinkName() {
		return getStr("link_name");
	}

	public void setLinkSort(java.lang.Integer linkSort) {
		set("link_sort", linkSort);
	}
	
	public java.lang.Integer getLinkSort() {
		return getInt("link_sort");
	}

	public void setLinkAddTime(java.lang.Long linkAddTime) {
		set("link_add_time", linkAddTime);
	}
	
	public java.lang.Long getLinkAddTime() {
		return getLong("link_add_time");
	}

	public void setLinkTime(java.lang.Long linkTime) {
		set("link_time", linkTime);
	}
	
	public java.lang.Long getLinkTime() {
		return getLong("link_time");
	}

	public void setLinkUrl(java.lang.String linkUrl) {
		set("link_url", linkUrl);
	}
	
	public java.lang.String getLinkUrl() {
		return getStr("link_url");
	}

	public void setLinkLogo(java.lang.String linkLogo) {
		set("link_logo", linkLogo);
	}
	
	public java.lang.String getLinkLogo() {
		return getStr("link_logo");
	}

}
