package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacCollect<M extends BaseMacCollect<M>> extends JbootModel<M> implements IBean {

	public void setCollectId(java.lang.Long collectId) {
		set("collect_id", collectId);
	}
	
	public java.lang.Long getCollectId() {
		return getLong("collect_id");
	}

	public void setCollectName(java.lang.String collectName) {
		set("collect_name", collectName);
	}
	
	public java.lang.String getCollectName() {
		return getStr("collect_name");
	}

	public void setCollectUrl(java.lang.String collectUrl) {
		set("collect_url", collectUrl);
	}
	
	public java.lang.String getCollectUrl() {
		return getStr("collect_url");
	}

	public void setCollectType(java.lang.Boolean collectType) {
		set("collect_type", collectType);
	}
	
	public java.lang.Boolean getCollectType() {
		return get("collect_type");
	}

	public void setCollectMid(java.lang.Boolean collectMid) {
		set("collect_mid", collectMid);
	}
	
	public java.lang.Boolean getCollectMid() {
		return get("collect_mid");
	}

	public void setCollectAppid(java.lang.String collectAppid) {
		set("collect_appid", collectAppid);
	}
	
	public java.lang.String getCollectAppid() {
		return getStr("collect_appid");
	}

	public void setCollectAppkey(java.lang.String collectAppkey) {
		set("collect_appkey", collectAppkey);
	}
	
	public java.lang.String getCollectAppkey() {
		return getStr("collect_appkey");
	}

	public void setCollectParam(java.lang.String collectParam) {
		set("collect_param", collectParam);
	}
	
	public java.lang.String getCollectParam() {
		return getStr("collect_param");
	}

}
