package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacCjNode<M extends BaseMacCjNode<M>> extends JbootModel<M> implements IBean {

	public void setNodeid(java.lang.Integer nodeid) {
		set("nodeid", nodeid);
	}
	
	public java.lang.Integer getNodeid() {
		return getInt("nodeid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setLastdate(java.lang.Long lastdate) {
		set("lastdate", lastdate);
	}
	
	public java.lang.Long getLastdate() {
		return getLong("lastdate");
	}

	public void setSourcecharset(java.lang.String sourcecharset) {
		set("sourcecharset", sourcecharset);
	}
	
	public java.lang.String getSourcecharset() {
		return getStr("sourcecharset");
	}

	public void setSourcetype(java.lang.Boolean sourcetype) {
		set("sourcetype", sourcetype);
	}
	
	public java.lang.Boolean getSourcetype() {
		return get("sourcetype");
	}

	public void setUrlpage(java.lang.String urlpage) {
		set("urlpage", urlpage);
	}
	
	public java.lang.String getUrlpage() {
		return getStr("urlpage");
	}

	public void setPagesizeStart(java.lang.Integer pagesizeStart) {
		set("pagesize_start", pagesizeStart);
	}
	
	public java.lang.Integer getPagesizeStart() {
		return getInt("pagesize_start");
	}

	public void setPagesizeEnd(java.lang.Integer pagesizeEnd) {
		set("pagesize_end", pagesizeEnd);
	}
	
	public java.lang.Integer getPagesizeEnd() {
		return getInt("pagesize_end");
	}

	public void setPageBase(java.lang.String pageBase) {
		set("page_base", pageBase);
	}
	
	public java.lang.String getPageBase() {
		return getStr("page_base");
	}

	public void setParNum(java.lang.Integer parNum) {
		set("par_num", parNum);
	}
	
	public java.lang.Integer getParNum() {
		return getInt("par_num");
	}

	public void setUrlContain(java.lang.String urlContain) {
		set("url_contain", urlContain);
	}
	
	public java.lang.String getUrlContain() {
		return getStr("url_contain");
	}

	public void setUrlExcept(java.lang.String urlExcept) {
		set("url_except", urlExcept);
	}
	
	public java.lang.String getUrlExcept() {
		return getStr("url_except");
	}

	public void setUrlStart(java.lang.String urlStart) {
		set("url_start", urlStart);
	}
	
	public java.lang.String getUrlStart() {
		return getStr("url_start");
	}

	public void setUrlEnd(java.lang.String urlEnd) {
		set("url_end", urlEnd);
	}
	
	public java.lang.String getUrlEnd() {
		return getStr("url_end");
	}

	public void setTitleRule(java.lang.String titleRule) {
		set("title_rule", titleRule);
	}
	
	public java.lang.String getTitleRule() {
		return getStr("title_rule");
	}

	public void setTitleHtmlRule(java.lang.String titleHtmlRule) {
		set("title_html_rule", titleHtmlRule);
	}
	
	public java.lang.String getTitleHtmlRule() {
		return getStr("title_html_rule");
	}

	public void setTypeRule(java.lang.String typeRule) {
		set("type_rule", typeRule);
	}
	
	public java.lang.String getTypeRule() {
		return getStr("type_rule");
	}

	public void setTypeHtmlRule(java.lang.String typeHtmlRule) {
		set("type_html_rule", typeHtmlRule);
	}
	
	public java.lang.String getTypeHtmlRule() {
		return getStr("type_html_rule");
	}

	public void setContentRule(java.lang.String contentRule) {
		set("content_rule", contentRule);
	}
	
	public java.lang.String getContentRule() {
		return getStr("content_rule");
	}

	public void setContentHtmlRule(java.lang.String contentHtmlRule) {
		set("content_html_rule", contentHtmlRule);
	}
	
	public java.lang.String getContentHtmlRule() {
		return getStr("content_html_rule");
	}

	public void setContentPageStart(java.lang.String contentPageStart) {
		set("content_page_start", contentPageStart);
	}
	
	public java.lang.String getContentPageStart() {
		return getStr("content_page_start");
	}

	public void setContentPageEnd(java.lang.String contentPageEnd) {
		set("content_page_end", contentPageEnd);
	}
	
	public java.lang.String getContentPageEnd() {
		return getStr("content_page_end");
	}

	public void setContentPageRule(java.lang.Boolean contentPageRule) {
		set("content_page_rule", contentPageRule);
	}
	
	public java.lang.Boolean getContentPageRule() {
		return get("content_page_rule");
	}

	public void setContentPage(java.lang.Boolean contentPage) {
		set("content_page", contentPage);
	}
	
	public java.lang.Boolean getContentPage() {
		return get("content_page");
	}

	public void setContentNextpage(java.lang.String contentNextpage) {
		set("content_nextpage", contentNextpage);
	}
	
	public java.lang.String getContentNextpage() {
		return getStr("content_nextpage");
	}

	public void setDownAttachment(java.lang.Boolean downAttachment) {
		set("down_attachment", downAttachment);
	}
	
	public java.lang.Boolean getDownAttachment() {
		return get("down_attachment");
	}

	public void setWatermark(java.lang.Boolean watermark) {
		set("watermark", watermark);
	}
	
	public java.lang.Boolean getWatermark() {
		return get("watermark");
	}

	public void setCollOrder(java.lang.Integer collOrder) {
		set("coll_order", collOrder);
	}
	
	public java.lang.Integer getCollOrder() {
		return getInt("coll_order");
	}

	public void setCustomizeConfig(java.lang.String customizeConfig) {
		set("customize_config", customizeConfig);
	}
	
	public java.lang.String getCustomizeConfig() {
		return getStr("customize_config");
	}

	public void setProgramConfig(java.lang.String programConfig) {
		set("program_config", programConfig);
	}
	
	public java.lang.String getProgramConfig() {
		return getStr("program_config");
	}

	public void setMid(java.lang.Boolean mid) {
		set("mid", mid);
	}
	
	public java.lang.Boolean getMid() {
		return get("mid");
	}

}
