package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacAdmin<M extends BaseMacAdmin<M>> extends JbootModel<M> implements IBean {

	public void setAdminId(java.lang.Integer adminId) {
		set("admin_id", adminId);
	}
	
	public java.lang.Integer getAdminId() {
		return getInt("admin_id");
	}

	public void setAdminName(java.lang.String adminName) {
		set("admin_name", adminName);
	}
	
	public java.lang.String getAdminName() {
		return getStr("admin_name");
	}

	public void setAdminPwd(java.lang.String adminPwd) {
		set("admin_pwd", adminPwd);
	}
	
	public java.lang.String getAdminPwd() {
		return getStr("admin_pwd");
	}

	public void setAdminRandom(java.lang.String adminRandom) {
		set("admin_random", adminRandom);
	}
	
	public java.lang.String getAdminRandom() {
		return getStr("admin_random");
	}

	public void setAdminStatus(java.lang.Boolean adminStatus) {
		set("admin_status", adminStatus);
	}
	
	public java.lang.Boolean getAdminStatus() {
		return get("admin_status");
	}

	public void setAdminAuth(java.lang.String adminAuth) {
		set("admin_auth", adminAuth);
	}
	
	public java.lang.String getAdminAuth() {
		return getStr("admin_auth");
	}

	public void setAdminLoginTime(java.lang.Long adminLoginTime) {
		set("admin_login_time", adminLoginTime);
	}
	
	public java.lang.Long getAdminLoginTime() {
		return getLong("admin_login_time");
	}

	public void setAdminLoginIp(java.lang.Long adminLoginIp) {
		set("admin_login_ip", adminLoginIp);
	}
	
	public java.lang.Long getAdminLoginIp() {
		return getLong("admin_login_ip");
	}

	public void setAdminLoginNum(java.lang.Long adminLoginNum) {
		set("admin_login_num", adminLoginNum);
	}
	
	public java.lang.Long getAdminLoginNum() {
		return getLong("admin_login_num");
	}

	public void setAdminLastLoginTime(java.lang.Long adminLastLoginTime) {
		set("admin_last_login_time", adminLastLoginTime);
	}
	
	public java.lang.Long getAdminLastLoginTime() {
		return getLong("admin_last_login_time");
	}

	public void setAdminLastLoginIp(java.lang.Long adminLastLoginIp) {
		set("admin_last_login_ip", adminLastLoginIp);
	}
	
	public java.lang.Long getAdminLastLoginIp() {
		return getLong("admin_last_login_ip");
	}

}
