package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacCjContent<M extends BaseMacCjContent<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setNodeid(java.lang.Long nodeid) {
		set("nodeid", nodeid);
	}
	
	public java.lang.Long getNodeid() {
		return getLong("nodeid");
	}

	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}
	
	public java.lang.Boolean getStatus() {
		return get("status");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setData(java.lang.String data) {
		set("data", data);
	}
	
	public java.lang.String getData() {
		return getStr("data");
	}

}
