package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacVod<M extends BaseMacVod<M>> extends JbootModel<M> implements IBean {

	public void setVodId(java.lang.Long vodId) {
		set("vod_id", vodId);
	}
	
	public java.lang.Long getVodId() {
		return getLong("vod_id");
	}

	public void setTypeId(java.lang.Integer typeId) {
		set("type_id", typeId);
	}
	
	public java.lang.Integer getTypeId() {
		return getInt("type_id");
	}

	public void setTypeId1(java.lang.Integer typeId1) {
		set("type_id_1", typeId1);
	}
	
	public java.lang.Integer getTypeId1() {
		return getInt("type_id_1");
	}

	public void setGroupId(java.lang.Integer groupId) {
		set("group_id", groupId);
	}
	
	public java.lang.Integer getGroupId() {
		return getInt("group_id");
	}

	public void setVodName(java.lang.String vodName) {
		set("vod_name", vodName);
	}
	
	public java.lang.String getVodName() {
		return getStr("vod_name");
	}

	public void setVodSub(java.lang.String vodSub) {
		set("vod_sub", vodSub);
	}
	
	public java.lang.String getVodSub() {
		return getStr("vod_sub");
	}

	public void setVodEn(java.lang.String vodEn) {
		set("vod_en", vodEn);
	}
	
	public java.lang.String getVodEn() {
		return getStr("vod_en");
	}

	public void setVodStatus(java.lang.String vodStatus) {
		set("vod_status", vodStatus);
	}
	
	public java.lang.String getVodStatus() {
		return get("vod_status");
	}

	public void setVodLetter(java.lang.String vodLetter) {
		set("vod_letter", vodLetter);
	}
	
	public java.lang.String getVodLetter() {
		return getStr("vod_letter");
	}

	public void setVodColor(java.lang.String vodColor) {
		set("vod_color", vodColor);
	}
	
	public java.lang.String getVodColor() {
		return getStr("vod_color");
	}

	public void setVodTag(java.lang.String vodTag) {
		set("vod_tag", vodTag);
	}
	
	public java.lang.String getVodTag() {
		return getStr("vod_tag");
	}

	public void setVodClass(java.lang.String vodClass) {
		set("vod_class", vodClass);
	}
	
	public java.lang.String getVodClass() {
		return getStr("vod_class");
	}

	public void setVodPic(java.lang.String vodPic) {
		set("vod_pic", vodPic);
	}
	
	public java.lang.String getVodPic() {
		return getStr("vod_pic");
	}

	public void setVodPicThumb(java.lang.String vodPicThumb) {
		set("vod_pic_thumb", vodPicThumb);
	}
	
	public java.lang.String getVodPicThumb() {
		return getStr("vod_pic_thumb");
	}

	public void setVodPicSlide(java.lang.String vodPicSlide) {
		set("vod_pic_slide", vodPicSlide);
	}
	
	public java.lang.String getVodPicSlide() {
		return getStr("vod_pic_slide");
	}

	public void setVodActor(java.lang.String vodActor) {
		set("vod_actor", vodActor);
	}
	
	public java.lang.String getVodActor() {
		return getStr("vod_actor");
	}

	public void setVodDirector(java.lang.String vodDirector) {
		set("vod_director", vodDirector);
	}
	
	public java.lang.String getVodDirector() {
		return getStr("vod_director");
	}

	public void setVodWriter(java.lang.String vodWriter) {
		set("vod_writer", vodWriter);
	}
	
	public java.lang.String getVodWriter() {
		return getStr("vod_writer");
	}

	public void setVodBlurb(java.lang.String vodBlurb) {
		set("vod_blurb", vodBlurb);
	}
	
	public java.lang.String getVodBlurb() {
		return getStr("vod_blurb");
	}

	public void setVodRemarks(java.lang.String vodRemarks) {
		set("vod_remarks", vodRemarks);
	}
	
	public java.lang.String getVodRemarks() {
		return getStr("vod_remarks");
	}

	public void setVodPubdate(java.lang.String vodPubdate) {
		set("vod_pubdate", vodPubdate);
	}
	
	public java.lang.String getVodPubdate() {
		return getStr("vod_pubdate");
	}

	public void setVodTotal(java.lang.Integer vodTotal) {
		set("vod_total", vodTotal);
	}
	
	public java.lang.Integer getVodTotal() {
		return getInt("vod_total");
	}

	public void setVodSerial(java.lang.String vodSerial) {
		set("vod_serial", vodSerial);
	}
	
	public java.lang.String getVodSerial() {
		return getStr("vod_serial");
	}

	public void setVodTv(java.lang.String vodTv) {
		set("vod_tv", vodTv);
	}
	
	public java.lang.String getVodTv() {
		return getStr("vod_tv");
	}

	public void setVodWeekday(java.lang.String vodWeekday) {
		set("vod_weekday", vodWeekday);
	}
	
	public java.lang.String getVodWeekday() {
		return getStr("vod_weekday");
	}

	public void setVodArea(java.lang.String vodArea) {
		set("vod_area", vodArea);
	}
	
	public java.lang.String getVodArea() {
		return getStr("vod_area");
	}

	public void setVodLang(java.lang.String vodLang) {
		set("vod_lang", vodLang);
	}
	
	public java.lang.String getVodLang() {
		return getStr("vod_lang");
	}

	public void setVodYear(java.lang.String vodYear) {
		set("vod_year", vodYear);
	}
	
	public java.lang.String getVodYear() {
		return getStr("vod_year");
	}

	public void setVodVersion(java.lang.String vodVersion) {
		set("vod_version", vodVersion);
	}
	
	public java.lang.String getVodVersion() {
		return getStr("vod_version");
	}

	public void setVodState(java.lang.String vodState) {
		set("vod_state", vodState);
	}
	
	public java.lang.String getVodState() {
		return getStr("vod_state");
	}

	public void setVodAuthor(java.lang.String vodAuthor) {
		set("vod_author", vodAuthor);
	}
	
	public java.lang.String getVodAuthor() {
		return getStr("vod_author");
	}

	public void setVodJumpurl(java.lang.String vodJumpurl) {
		set("vod_jumpurl", vodJumpurl);
	}
	
	public java.lang.String getVodJumpurl() {
		return getStr("vod_jumpurl");
	}

	public void setVodTpl(java.lang.String vodTpl) {
		set("vod_tpl", vodTpl);
	}
	
	public java.lang.String getVodTpl() {
		return getStr("vod_tpl");
	}

	public void setVodTplPlay(java.lang.String vodTplPlay) {
		set("vod_tpl_play", vodTplPlay);
	}
	
	public java.lang.String getVodTplPlay() {
		return getStr("vod_tpl_play");
	}

	public void setVodTplDown(java.lang.String vodTplDown) {
		set("vod_tpl_down", vodTplDown);
	}
	
	public java.lang.String getVodTplDown() {
		return getStr("vod_tpl_down");
	}

	public void setVodIsend(java.lang.String vodIsend) {
		set("vod_isend", vodIsend);
	}
	
	public java.lang.String getVodIsend() {
		return get("vod_isend");
	}

	public void setVodLock(java.lang.String vodLock) {
		set("vod_lock", vodLock);
	}
	
	public java.lang.String getVodLock() {
		return get("vod_lock");
	}

	public void setVodLevel(java.lang.String vodLevel) {
		set("vod_level", vodLevel);
	}
	
	public java.lang.String getVodLevel() {
		return get("vod_level");
	}

	public void setVodPointsPlay(java.lang.Integer vodPointsPlay) {
		set("vod_points_play", vodPointsPlay);
	}
	
	public java.lang.Integer getVodPointsPlay() {
		return getInt("vod_points_play");
	}

	public void setVodPointsDown(java.lang.Integer vodPointsDown) {
		set("vod_points_down", vodPointsDown);
	}
	
	public java.lang.Integer getVodPointsDown() {
		return getInt("vod_points_down");
	}

	public void setVodHits(java.lang.Integer vodHits) {
		set("vod_hits", vodHits);
	}
	
	public java.lang.Integer getVodHits() {
		return getInt("vod_hits");
	}

	public void setVodHitsDay(java.lang.Integer vodHitsDay) {
		set("vod_hits_day", vodHitsDay);
	}
	
	public java.lang.Integer getVodHitsDay() {
		return getInt("vod_hits_day");
	}

	public void setVodHitsWeek(java.lang.Integer vodHitsWeek) {
		set("vod_hits_week", vodHitsWeek);
	}
	
	public java.lang.Integer getVodHitsWeek() {
		return getInt("vod_hits_week");
	}

	public void setVodHitsMonth(java.lang.Integer vodHitsMonth) {
		set("vod_hits_month", vodHitsMonth);
	}
	
	public java.lang.Integer getVodHitsMonth() {
		return getInt("vod_hits_month");
	}

	public void setVodDuration(java.lang.String vodDuration) {
		set("vod_duration", vodDuration);
	}
	
	public java.lang.String getVodDuration() {
		return getStr("vod_duration");
	}

	public void setVodUp(java.lang.Integer vodUp) {
		set("vod_up", vodUp);
	}
	
	public java.lang.Integer getVodUp() {
		return getInt("vod_up");
	}

	public void setVodDown(java.lang.Integer vodDown) {
		set("vod_down", vodDown);
	}
	
	public java.lang.Integer getVodDown() {
		return getInt("vod_down");
	}

	public void setVodScore(java.math.BigDecimal vodScore) {
		set("vod_score", vodScore);
	}
	
	public java.math.BigDecimal getVodScore() {
		return get("vod_score");
	}

	public void setVodScoreAll(java.lang.Integer vodScoreAll) {
		set("vod_score_all", vodScoreAll);
	}
	
	public java.lang.Integer getVodScoreAll() {
		return getInt("vod_score_all");
	}

	public void setVodScoreNum(java.lang.Integer vodScoreNum) {
		set("vod_score_num", vodScoreNum);
	}
	
	public java.lang.Integer getVodScoreNum() {
		return getInt("vod_score_num");
	}

	public void setVodTime(java.util.Date vodTime) {
		set("vod_time", vodTime);
	}
	
	public java.util.Date getVodTime() {
		return get("vod_time");
	}

	public void setVodTimeAdd(java.util.Date vodTimeAdd) {
		set("vod_time_add", vodTimeAdd);
	}
	
	public java.util.Date getVodTimeAdd() {
		return get("vod_time_add");
	}

	public void setVodTimeHits(java.util.Date vodTimeHits) {
		set("vod_time_hits", vodTimeHits);
	}
	
	public java.util.Date getVodTimeHits() {
		return get("vod_time_hits");
	}

	public void setVodTimeMake(java.lang.Long vodTimeMake) {
		set("vod_time_make", vodTimeMake);
	}
	
	public java.lang.Long getVodTimeMake() {
		return getLong("vod_time_make");
	}

	public void setVodTrysee(java.lang.Integer vodTrysee) {
		set("vod_trysee", vodTrysee);
	}
	
	public java.lang.Integer getVodTrysee() {
		return getInt("vod_trysee");
	}

	public void setVodDoubanId(java.lang.Long vodDoubanId) {
		set("vod_douban_id", vodDoubanId);
	}
	
	public java.lang.Long getVodDoubanId() {
		return getLong("vod_douban_id");
	}

	public void setVodDoubanScore(java.math.BigDecimal vodDoubanScore) {
		set("vod_douban_score", vodDoubanScore);
	}
	
	public java.math.BigDecimal getVodDoubanScore() {
		return get("vod_douban_score");
	}

	public void setVodReurl(java.lang.String vodReurl) {
		set("vod_reurl", vodReurl);
	}
	
	public java.lang.String getVodReurl() {
		return getStr("vod_reurl");
	}

	public void setVodRelVod(java.lang.String vodRelVod) {
		set("vod_rel_vod", vodRelVod);
	}
	
	public java.lang.String getVodRelVod() {
		return getStr("vod_rel_vod");
	}

	public void setVodRelArt(java.lang.String vodRelArt) {
		set("vod_rel_art", vodRelArt);
	}
	
	public java.lang.String getVodRelArt() {
		return getStr("vod_rel_art");
	}

	public void setVodContent(java.lang.String vodContent) {
		set("vod_content", vodContent);
	}
	
	public java.lang.String getVodContent() {
		return getStr("vod_content");
	}

	public void setVodPlayFrom(java.lang.String vodPlayFrom) {
		set("vod_play_from", vodPlayFrom);
	}
	
	public java.lang.String getVodPlayFrom() {
		return getStr("vod_play_from");
	}

	public void setVodPlayServer(java.lang.String vodPlayServer) {
		set("vod_play_server", vodPlayServer);
	}
	
	public java.lang.String getVodPlayServer() {
		return getStr("vod_play_server");
	}

	public void setVodPlayNote(java.lang.String vodPlayNote) {
		set("vod_play_note", vodPlayNote);
	}
	
	public java.lang.String getVodPlayNote() {
		return getStr("vod_play_note");
	}

	public void setVodPlayUrl(java.lang.String vodPlayUrl) {
		set("vod_play_url", vodPlayUrl);
	}
	
	public java.lang.String getVodPlayUrl() {
		return getStr("vod_play_url");
	}

	public void setVodDownFrom(java.lang.String vodDownFrom) {
		set("vod_down_from", vodDownFrom);
	}
	
	public java.lang.String getVodDownFrom() {
		return getStr("vod_down_from");
	}

	public void setVodDownServer(java.lang.String vodDownServer) {
		set("vod_down_server", vodDownServer);
	}
	
	public java.lang.String getVodDownServer() {
		return getStr("vod_down_server");
	}

	public void setVodDownNote(java.lang.String vodDownNote) {
		set("vod_down_note", vodDownNote);
	}
	
	public java.lang.String getVodDownNote() {
		return getStr("vod_down_note");
	}

	public void setVodDownUrl(java.lang.String vodDownUrl) {
		set("vod_down_url", vodDownUrl);
	}
	
	public java.lang.String getVodDownUrl() {
		return getStr("vod_down_url");
	}

}
