package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacTopic<M extends BaseMacTopic<M>> extends JbootModel<M> implements IBean {

	public void setTopicId(java.lang.Integer topicId) {
		set("topic_id", topicId);
	}
	
	public java.lang.Integer getTopicId() {
		return getInt("topic_id");
	}

	public void setTopicName(java.lang.String topicName) {
		set("topic_name", topicName);
	}
	
	public java.lang.String getTopicName() {
		return getStr("topic_name");
	}

	public void setTopicEn(java.lang.String topicEn) {
		set("topic_en", topicEn);
	}
	
	public java.lang.String getTopicEn() {
		return getStr("topic_en");
	}

	public void setTopicSub(java.lang.String topicSub) {
		set("topic_sub", topicSub);
	}
	
	public java.lang.String getTopicSub() {
		return getStr("topic_sub");
	}

	public void setTopicStatus(java.lang.Boolean topicStatus) {
		set("topic_status", topicStatus);
	}
	
	public java.lang.Boolean getTopicStatus() {
		return get("topic_status");
	}

	public void setTopicSort(java.lang.Integer topicSort) {
		set("topic_sort", topicSort);
	}
	
	public java.lang.Integer getTopicSort() {
		return getInt("topic_sort");
	}

	public void setTopicLetter(java.lang.String topicLetter) {
		set("topic_letter", topicLetter);
	}
	
	public java.lang.String getTopicLetter() {
		return getStr("topic_letter");
	}

	public void setTopicColor(java.lang.String topicColor) {
		set("topic_color", topicColor);
	}
	
	public java.lang.String getTopicColor() {
		return getStr("topic_color");
	}

	public void setTopicTpl(java.lang.String topicTpl) {
		set("topic_tpl", topicTpl);
	}
	
	public java.lang.String getTopicTpl() {
		return getStr("topic_tpl");
	}

	public void setTopicType(java.lang.String topicType) {
		set("topic_type", topicType);
	}
	
	public java.lang.String getTopicType() {
		return getStr("topic_type");
	}

	public void setTopicPic(java.lang.String topicPic) {
		set("topic_pic", topicPic);
	}
	
	public java.lang.String getTopicPic() {
		return getStr("topic_pic");
	}

	public void setTopicPicThumb(java.lang.String topicPicThumb) {
		set("topic_pic_thumb", topicPicThumb);
	}
	
	public java.lang.String getTopicPicThumb() {
		return getStr("topic_pic_thumb");
	}

	public void setTopicPicSlide(java.lang.String topicPicSlide) {
		set("topic_pic_slide", topicPicSlide);
	}
	
	public java.lang.String getTopicPicSlide() {
		return getStr("topic_pic_slide");
	}

	public void setTopicKey(java.lang.String topicKey) {
		set("topic_key", topicKey);
	}
	
	public java.lang.String getTopicKey() {
		return getStr("topic_key");
	}

	public void setTopicDes(java.lang.String topicDes) {
		set("topic_des", topicDes);
	}
	
	public java.lang.String getTopicDes() {
		return getStr("topic_des");
	}

	public void setTopicTitle(java.lang.String topicTitle) {
		set("topic_title", topicTitle);
	}
	
	public java.lang.String getTopicTitle() {
		return getStr("topic_title");
	}

	public void setTopicBlurb(java.lang.String topicBlurb) {
		set("topic_blurb", topicBlurb);
	}
	
	public java.lang.String getTopicBlurb() {
		return getStr("topic_blurb");
	}

	public void setTopicRemarks(java.lang.String topicRemarks) {
		set("topic_remarks", topicRemarks);
	}
	
	public java.lang.String getTopicRemarks() {
		return getStr("topic_remarks");
	}

	public void setTopicLevel(java.lang.Boolean topicLevel) {
		set("topic_level", topicLevel);
	}
	
	public java.lang.Boolean getTopicLevel() {
		return get("topic_level");
	}

	public void setTopicUp(java.lang.Integer topicUp) {
		set("topic_up", topicUp);
	}
	
	public java.lang.Integer getTopicUp() {
		return getInt("topic_up");
	}

	public void setTopicDown(java.lang.Integer topicDown) {
		set("topic_down", topicDown);
	}
	
	public java.lang.Integer getTopicDown() {
		return getInt("topic_down");
	}

	public void setTopicScore(java.math.BigDecimal topicScore) {
		set("topic_score", topicScore);
	}
	
	public java.math.BigDecimal getTopicScore() {
		return get("topic_score");
	}

	public void setTopicScoreAll(java.lang.Integer topicScoreAll) {
		set("topic_score_all", topicScoreAll);
	}
	
	public java.lang.Integer getTopicScoreAll() {
		return getInt("topic_score_all");
	}

	public void setTopicScoreNum(java.lang.Integer topicScoreNum) {
		set("topic_score_num", topicScoreNum);
	}
	
	public java.lang.Integer getTopicScoreNum() {
		return getInt("topic_score_num");
	}

	public void setTopicHits(java.lang.Integer topicHits) {
		set("topic_hits", topicHits);
	}
	
	public java.lang.Integer getTopicHits() {
		return getInt("topic_hits");
	}

	public void setTopicHitsDay(java.lang.Integer topicHitsDay) {
		set("topic_hits_day", topicHitsDay);
	}
	
	public java.lang.Integer getTopicHitsDay() {
		return getInt("topic_hits_day");
	}

	public void setTopicHitsWeek(java.lang.Integer topicHitsWeek) {
		set("topic_hits_week", topicHitsWeek);
	}
	
	public java.lang.Integer getTopicHitsWeek() {
		return getInt("topic_hits_week");
	}

	public void setTopicHitsMonth(java.lang.Integer topicHitsMonth) {
		set("topic_hits_month", topicHitsMonth);
	}
	
	public java.lang.Integer getTopicHitsMonth() {
		return getInt("topic_hits_month");
	}

	public void setTopicTime(java.lang.Long topicTime) {
		set("topic_time", topicTime);
	}
	
	public java.lang.Long getTopicTime() {
		return getLong("topic_time");
	}

	public void setTopicTimeAdd(java.lang.Long topicTimeAdd) {
		set("topic_time_add", topicTimeAdd);
	}
	
	public java.lang.Long getTopicTimeAdd() {
		return getLong("topic_time_add");
	}

	public void setTopicTimeHits(java.lang.Long topicTimeHits) {
		set("topic_time_hits", topicTimeHits);
	}
	
	public java.lang.Long getTopicTimeHits() {
		return getLong("topic_time_hits");
	}

	public void setTopicTimeMake(java.lang.Long topicTimeMake) {
		set("topic_time_make", topicTimeMake);
	}
	
	public java.lang.Long getTopicTimeMake() {
		return getLong("topic_time_make");
	}

	public void setTopicTag(java.lang.String topicTag) {
		set("topic_tag", topicTag);
	}
	
	public java.lang.String getTopicTag() {
		return getStr("topic_tag");
	}

	public void setTopicRelVod(java.lang.String topicRelVod) {
		set("topic_rel_vod", topicRelVod);
	}
	
	public java.lang.String getTopicRelVod() {
		return getStr("topic_rel_vod");
	}

	public void setTopicRelArt(java.lang.String topicRelArt) {
		set("topic_rel_art", topicRelArt);
	}
	
	public java.lang.String getTopicRelArt() {
		return getStr("topic_rel_art");
	}

	public void setTopicContent(java.lang.String topicContent) {
		set("topic_content", topicContent);
	}
	
	public java.lang.String getTopicContent() {
		return getStr("topic_content");
	}

	public void setTopicExtend(java.lang.String topicExtend) {
		set("topic_extend", topicExtend);
	}
	
	public java.lang.String getTopicExtend() {
		return getStr("topic_extend");
	}

}
