package com.lzx.movie.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMacVisit<M extends BaseMacVisit<M>> extends JbootModel<M> implements IBean {

	public void setVisitId(java.lang.Long visitId) {
		set("visit_id", visitId);
	}
	
	public java.lang.Long getVisitId() {
		return getLong("visit_id");
	}

	public void setUserId(java.lang.Long userId) {
		set("user_id", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("user_id");
	}

	public void setVisitIp(java.lang.Long visitIp) {
		set("visit_ip", visitIp);
	}
	
	public java.lang.Long getVisitIp() {
		return getLong("visit_ip");
	}

	public void setVisitLy(java.lang.String visitLy) {
		set("visit_ly", visitLy);
	}
	
	public java.lang.String getVisitLy() {
		return getStr("visit_ly");
	}

	public void setVisitTime(java.lang.Long visitTime) {
		set("visit_time", visitTime);
	}
	
	public java.lang.Long getVisitTime() {
		return getLong("visit_time");
	}

}
