package com.lzx.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.admin.service.entity.model.base.BaseLog;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_log", primaryKey = "id")
public class Log extends BaseLog<Log> {
	
}
