package com.lzx.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import com.lzx.admin.service.entity.model.base.BaseUserRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_user_role", primaryKey = "id")
public class UserRole extends BaseUserRole<UserRole> {
	
}
