package com.lzx.admin.service.entity.model;

import io.jboot.db.annotation.Table;

import java.util.List;

import com.lzx.admin.service.entity.model.base.BaseUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_user", primaryKey = "id")
public class User extends BaseUser<User> {
	
	
	private List<Role> roles;

	public List<Role> getRoles() {
		return roles;
	}

	public void setRoles(List<Role> roles) {
		this.roles = roles;
	}

	
	
	
	
}
